---
# import tasks file to initiate the patching
- name: Defining patching Type
  ansible.builtin.debug:
    msg: "Patching_type: {{ Patching_type }}"

- name: Importing full patching
  ansible.builtin.import_tasks: update_with_reboot.yml
  when: Patching_type == "KERNEL"

- name: Importing NOREBOOT patching
  ansible.builtin.import_tasks: update_NO_reboot.yml
  when: Patching_type == "NOREBOOT"

